music_app/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users, only:[:new, :create, :show]
  resource :session, only:[:new, :create, :destroy]
  resources :bands do
    resources :albums, only: [:new]
  end
  resources :albums, only:[:create, :edit, :show, :update, :destroy]
end

music_app/app/models/album.rb
# == Schema Information
#
# Table name: albums
#
#  id         :bigint(8)        not null, primary key
#  title      :string           not null
#  band_id    :integer          not null
#  live       :boolean          default(FALSE), not null
#  year       :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Album < ApplicationRecord

  validates :title, :band_id, :year, presence: true
  validates :live, inclusion: { in: [true, false] }

  belongs_to :band,
    class_name: 'Band',
    foreign_key: :band_id
end

music_app/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

music_app/app/models/band.rb
# == Schema Information
#
# Table name: bands
#
#  id         :bigint(8)        not null, primary key
#  name       :string           not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Band < ApplicationRecord

  validates :name, presence: true, uniqueness: true

  has_many :albums,
    class_name: 'Album',
    foreign_key: :band_id
end

music_app/app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :bigint(8)        not null, primary key
#  email           :string           not null
#  session_token   :string           not null
#  password_digest :string           not null
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#

class User < ApplicationRecord
  validates :email, :session_token, :password_digest, presence: true
  validates :password, length: { minimum: 6, allow_nil: true }

  attr_reader :password

  after_initialize :ensure_session_token
  #FIG VAPER

  def self.find_by_credentials(email, password)
    user = User.find_by(email: email)
    return nil unless user && user.is_password?(password)
    user
  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end

  def reset_session_token!
    self.update!(session_token: self.class.generate_session_token)
    self.session_token
  end

  private
  def ensure_session_token
    self.session_token ||= self.class.generate_session_token
  end

  def self.generate_session_token
    SecureRandom::urlsafe_base64(16)
  end
end

music_app/app/controllers/albums_controller.rb
class AlbumsController < ApplicationController

  def show
    @album = Album.find(params[:id])
    render :show
  end

  def new
    @band = Band.find(params[:band_id])
    @album = Album.new(band_id: params[:band_id])
    render :new
  end

  def create
    @album = Album.new(album_params)
    if @album.save
      redirect_to bands_url
    else
      flash.now[:errors] = @album.errors.full_messages
      render :new
    end
  end

  def edit
    @album = Album.find(params[:id])
    render :edit
  end

  def update
    @album = Album.find(params[:id])
    if @album.update(album_params)
      render :show
    else
      flash.now[:errors] = @album.errors.full_messages
      render :edit
    end
  end

  private
  def album_params
    params.require(:album).permit(:title, :band_id, :live, :year)
  end

end

music_app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # protect_from_forgery with: :exception

  helper_method :current_user, :logged_in?

  private
  def require_user!
    redirect_to new_session_url if current_user.nil?
  end

  def current_user
    return nil unless session[:session_token]
    @current_user ||= User.find_by(session_token: session[:session_token])
  end

  def logged_in?
    !current_user.nil?
  end

  def login_user!(user)
    session[:session_token] = user.reset_session_token!
    user.save!
    current_user
  end
end

music_app/app/controllers/bands_controller.rb
class BandsController < ApplicationController

  def index
    @bands = Band.all.order(:name)
    render :index
  end

  def create
    band = Band.new(band_params)
    if band.save
      @band = band
      redirect_to bands_url
    else
      flash.now[:errors] = band.errors.full_messages
      render :new
    end
  end

  def new
    render :new
  end

  def show
    @band = Band.find(params[:id])
    render :show
  end

  def edit
    @band = Band.find(params[:id])
    render :edit
  end

  def update
    @band = Band.find(params[:id])
    if @band.update(band_params)
      render :show
    else
      flash.now[:errors] = @band.errors.full_messages
      render :edit
    end
  end

  def destroy
    @band = Band.find(params[:id])
    @band.delete
    redirect_to bands_url
  end

  private
  def band_params
    params.require(:band).permit(:name)
  end


end

music_app/app/controllers/sessions_controller.rb
class SessionsController <ApplicationController
  def new
    render :new
  end

  def create
    username = params[:user][:email]
    password = params[:user][:password]
    @user = User.find_by_credentials(username, password)
    if @user 
      login_user!(@user)
      redirect_to user_url(@user)
    else
      flash.now[:errors] = ["Invalid Password"]
      render :new
    end

  end

  def destroy
    current_user.reset_session_token!
    session[:session_token] = nil
    redirect_to new_session_url
  end

end

music_app/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    user = User.new
    render :new
  end

  def create
    @user = User.new(user_params)
    if @user.save!
      login_user!(@user)
      redirect_to user_url(@user)
    else
      flash.now[:errors] = @user.errors.full_messages
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
    redirect_to bands_url
  end

  private
  def user_params
    params.require(:user).permit(:email, :password)
  end

end

music_app/app/helpers/application_helper.rb
module ApplicationHelper
  def auth_token
    "<input type='hidden' name='authenticity_token' value='#{form_authenticity_token}'>".html_safe 
  end
end

music_app/app/views/albums/edit.html.erb
<h2>Edit Album</h2>
<form action="<%= album_url %>" method="POST">
  <input type="hidden" name="_method" value="PATCH">
  <%= auth_token %>
  <table>
    <tr>
      <td>Title:</td>
      <td><input type="text" name="album[title]" value="<%= @album.title %>"></td>
    </tr>
    <tr>
      <td>Band:</td>
      <td>
        <select name="album[band_id]">
          <option value="0"<% " selected" if @album.band_id %>>Select a band...</option>
          <% bands = Band.all.order(:name) %>
          <% bands.each do |band| %>
          <option value="<%= band.id %>"<%= " selected" if band.id == @album.band_id %>><%= band.name %></option>
          <% end %>
        </select>
      </td>
    </tr>
    <tr>
      <td>Year:</td>
      <td><input type="text" name="album[year]" value="<%= @album.year %>">
    </tr>
    <tr>
      <td>Type:</td>
      <td>
        <label for="type_studio"><input type="radio" id="type_studio" name="album[live]" value="false"<%= " checked" if !@album.live %>> Studio</label>
        <label for="type_live"><input type="radio" id="type_live" name="album[live]" value="true"<%= " checked" if @album.live %>> Live</label>
      </td>
    </tr>
    <tr>
      <td colspan="2" align="right"><input type="submit" value="Save Changess"></td>
    </tr>
  </table>
</form>
<h5><a href="<%= band_url(@album.band_id) %>">Back to Band</a></h5>

music_app/app/views/albums/new.html.erb
<h2>Enter a New Album</h2>
<form action="<%= albums_url %>" method="POST">
  <%= auth_token %>
  <table>
    <tr>
      <td>Title:</td>
      <td><input type="text" name="album[title]"></td>
    </tr>
    <tr>
      <td>Band:</td>
      <td>
        <select name="album[band_id]">
          <option value="0" selected>Select a band...</option>
          <% bands = Band.all.order(:name) %>
          <% bands.each do |band| %>
          <option value="<%= band.id %>""<%= " selected" if band.id == @album.band_id %>><%= band.name %></option>
          <% end %>
        </select>
      </td>
    </tr>
    <tr>
      <td>Year:</td>
      <td><input type="text" name="album[year]" value="<%= @album.year %>">
    </tr>
    <tr>
      <td>Type:</td>
      <td>
        <label for="type_studio"><input type="radio" id="type_studio" name="album[live]" value="false" checked> Studio</label>
        <label for="type_live"><input type="radio" id="type_live" name="album[live]" value="true"> Live</label>
      </td>
    </tr>
    <tr>
      <td colspan="2" align="right"><input type="submit" value="Create Album"></td>
    </tr>
  </table>
</form>
<h5><a href="<%= band_url(@album.band_id) %>">Back to Band</a></h5>

music_app/app/views/albums/show.html.erb
<h2><%= @album.title %></h2>
<p><a href="<%= edit_album_url(@album) %>">Edit</a></p>
<form class="user" action="<%= album_url %>" method="POST">
  <%= auth_token %>
  <input type="hidden" name="_method" value="DELETE">
  <input type="submit" value="Delete">
</form>
<h5><a href="<%= band_url(@band) %>">Back to Bands</a></h5>

music_app/app/views/bands/edit.html.erb
<h2>Edit</h2>
<form action="<%= band_url %>" method="POST">
<input type="hidden" name="_method" value="PATCH">
  <%= auth_token %>
  <table>
    <tr>
      <td>Name:</td>
      <td><input type="text" name="band[name]" value="<%= @band.name %>"></td>
    </tr>
    <tr>
      <td colspan="2" align="right"><input type="submit" value="Save Changes"></td>
    </tr>
  </table>
</form>
<h5><a href="<%= bands_url %>">Back to All Bands</a></h5>

music_app/app/views/bands/index.html.erb
<h2>All Bands</h2>
<p><a href="<%= new_band_url %>">Add a new Band</a</p>
<ul>
<% @bands.each do |band| %>
  <li><a href="<%= band_url(band) %>"><%= band.name %></li>
<% end %>
</ul>

music_app/app/views/bands/new.html.erb
<h2>Enter a New Band</h2>
<form action="<%= bands_url %>" method="POST">
  <%= auth_token %>
  <table>
    <tr>
      <td>Name:</td>
      <td><input type="text" name="band[name]"></td>
    </tr>
    <tr>
      <td colspan="2" align="right"><input type="submit" value="Create Band"></td>
    </tr>
  </table>
</form>
<h5><a href="<%= bands_url %>">Back to All Bands</a></h5>

music_app/app/views/bands/show.html.erb
<h2><%= @band.name %></h2>
<p><a href="<%= edit_band_url(@band) %>">Edit Band</a></p>
<% if @band.albums.length > 0 %>
<ul>
  <% @band.albums.each do |album| %>
    <li><a href="<%= edit_album_url(album) %>"><%= album.title %></a></li>
    <% end %>
  <% end %>
  <li style="margin-top: 5px;"><a href="<%= new_band_album_url(@band) %>">Add a new album</a></li>
</ul>
<form class="user" action="<%= band_url %>" method="POST">
  <%= auth_token %>
  <input type="hidden" name="_method" value="DELETE">
  <input type="submit" value="Delete">
</form>
<h5><a href="<%= bands_url %>">Back to All Bands</a></h5>

music_app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MusicApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <h1>Music App</h1>
    <% if logged_in? %>
      <section class="user_block">
      <h4 class="user">Logged in as <%= current_user.email %>
      <form class="user" action="<%= session_url %>" method="POST">
        <%= auth_token %>
        <input type="hidden" name="_method" value="DELETE">
        <input type="submit" value="Logout">
      </form></h4>
      </section>
    <% end %>
    <hr>
    <% if flash[:errors] %>
        <p class="errors"><%= flash[:errors].join(", ") %></p>
      <% end %>
    <%= yield %>
  </body>
</html>

music_app/app/views/users/new.html.erb
<h2>Sign up</h2>
<form action="<%= users_url %>" METHOD="POST">
  <%= auth_token %>
  <table>
    <tr>
      <td>Email: </td>
      <td><input type="text" id="get_email" name="user[email]"></td>
    </tr>
    <tr>
      <td>Password: </td>
      <td><input type="password" id="get_password" name="user[password]"></td>
    <tr>
      <td>&nbsp;</td>
      <td><input type="submit" value="Create account"></td>
    </tr>
     <tr>
      <td colspan="2"><h5>Already have an account? <a href="<%= new_session_url %>">Log in</a></h5></td>
    </tr>
  </table>
</form>

music_app/app/views/users/show.html.erb
<%= @user.email %>